name: Build Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Build
      run: |
        pnpm install
        pnpm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: public
        folder: dist
        clean: false # Preserve existing files, only replace if named the same
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
